Repository sealsystems/node-consul, pull requests merged in 2019-10, with the labels that each got.

#11 Remove consul for cloud
  .vscode/launch.json
  README.md
  lib/cloud/cloudServicePort.js
  lib/cloud/index.js
  lib/cloud/lookup.js
  lib/cloud/resolveService.js
  lib/consul.js
  lib/consul/connect.js
  lib/consul/dnsWrapper.js
  lib/consul/getConfiguration.js
  lib/consul/getConsulId.js
  lib/consul/getHostname.js
  lib/consul/getMember.js
  lib/consul/getNodes.js
  lib/consul/heartbeat.js
  lib/consul/index.js
  lib/consul/initialize.js
  lib/consul/lookup.js
  lib/consul/resolveService.js
  lib/consul/serviceVersionAsTag.js
  lib/errors.js
  lib/inCloud.js
  package-lock.json
  package.json
  test/cloud/cloudServicePortTest.js
  test/cloud/consulTest.js
  test/cloud/lookupTest.js
  test/cloud/resolveServiceTest.js
  test/consul/connectTest.js
  test/consul/consulTest.js
  test/consul/getConfigationTest.js
  test/consul/getConsulIdTest.js
  test/consul/getHostnameTest.js
  test/consul/getMemberTest.js
  test/consul/getNodesTest.js
  test/consul/heartbeatTest.js
  test/consul/initializeTest.js
  test/consul/lookupTest.js
  test/consul/resolveServiceTest.js
  test/inCloudTest.js
  test/kv/delTest.js
  test/kv/getTest.js
  test/kv/setTest.js
  test/util/EventEmitterTest.js
  test/util/filterByStatusTest.js
  test/util/getConsulOptionsTest.js
  test/watch/kvTest.js
  test/watch/serviceTest.js
Labels: release/major

#13 fix: fixed bug in cloud version of resolveService
  lib/cloud/index.js
  lib/cloud/lookup.js
  lib/cloud/resolveService.js
  lib/consul/index.js
  lib/consul/resolveService.js
  lib/util/dnsWrapper.js
  lib/util/lookup.js
  package-lock.json
  package.json
  test/cloud/lookupTest.js
  test/cloud/resolveServiceTest.js
  test/consul/resolveServiceTest.js
  test/util/lookupTest.js
Labels: release/fix, release/patch

#14 feat: PLS-431
  .circleci/config.yml
  .eslintrc.json
  .github/pull_request_template.md
  .gitignore
  LICENSE
  appveyor.yml
  package-lock.json
  package.json
  test/mocha.opts
Labels: release/feat, release/minor
