Repository sealsystems/node-consul, pull requests merged in 2023-04, with the labels that each got.

#521 Update build configuration
  package-lock.json
Labels: automatic-merge

#522 Update build configuration
  package-lock.json
  package.json
Labels: automatic-merge

#523 Update build configuration
  package-lock.json
Labels: automatic-merge

#524 Update build configuration
  package-lock.json
Labels: automatic-merge

#526 Update build configuration
  package-lock.json
Labels: automatic-merge

#527 Update build configuration
  package-lock.json
Labels: automatic-merge

#528 Update build configuration
  package-lock.json
Labels: automatic-merge

#529 Update build configuration
  package-lock.json
Labels: automatic-merge

#530 Update build configuration
  package-lock.json
Labels: automatic-merge

#531 Update build configuration
  package-lock.json
Labels: automatic-merge

#532 Update build configuration
  package-lock.json
Labels: automatic-merge

#533 Update build configuration
  package-lock.json
Labels: automatic-merge

#534 Update build configuration
  package-lock.json
Labels: automatic-merge

#535 feat: Added setEnv method
  README.md
  lib/cloud/index.js
  lib/consul/getHostname.js
  lib/consul/index.js
  lib/consul/setEnv.js
  lib/util/consulUrl.js
  lib/watch/kv.js
  package-lock.json
  package.json
  test/cloud/consulTest.js
  test/consul/getNodesTest.js
  test/consul/initializeTest.js
  test/consul/resolveServiceTest.js
  test/consul/setEnvTest.js
  test/util/consulUrlTest.js
  test/watch/kvTest.js
  test/watch/serviceTest.js
Labels: release/minor, release/feat

#536 chore: Fixed test for windows
  test/consul/setEnvTest.js
Labels: release/patch, release/chore

#537 chore: next try to fix windows test
  lib/consul/setEnv.js
  test/consul/setEnvTest.js
Labels: release/patch, release/chore

#538 chore: Added default file paths
  README.md
  lib/consul/setEnv.js
  lib/util/consulUrl.js
  test/util/consulUrlTest.js
Labels: release/patch, release/chore

#539 Update build configuration
  package-lock.json
Labels: automatic-merge

#540 Update build configuration
  package-lock.json
Labels: automatic-merge

#541 Update build configuration
  package-lock.json
Labels: automatic-merge

#542 Update build configuration
  package-lock.json
Labels: automatic-merge

#543 Update build configuration
  package-lock.json
Labels: automatic-merge

#545 Update build configuration
  package-lock.json
Labels: automatic-merge

#546 Update build configuration
  package-lock.json
Labels: automatic-merge
